services:
  # Web service configuration
  - type: web
    name: mara-claim-system
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: mara-claim-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true

  # Database configuration
databases:
  - name: mara-claim-db
    plan: free
    ipAllowList: [] # Allow all IPs to connect